/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DeviceType = IDL.Variant({
  'tablet' : IDL.Null,
  'computer' : IDL.Null,
  'phone' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
});
export const HealthMetrics = IDL.Record({
  'bmi' : IDL.Opt(IDL.Float64),
  'sleepHoursPerNight' : IDL.Opt(IDL.Float64),
  'eyeStrainSymptoms' : IDL.Opt(IDL.Bool),
  'exerciseHoursPerWeek' : IDL.Opt(IDL.Float64),
});
export const Time = IDL.Int;
export const ScreenTimeEntry = IDL.Record({
  'minutes' : IDL.Nat,
  'device' : DeviceType,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addScreenTimeEntry' : IDL.Func([DeviceType, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHealthMetrics' : IDL.Func([], [IDL.Opt(HealthMetrics)], ['query']),
  'getRiskScore' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
  'getScreenTime' : IDL.Func([], [IDL.Vec(ScreenTimeEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitHealthMetrics' : IDL.Func([HealthMetrics], [], []),
  'updateRiskScore' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DeviceType = IDL.Variant({
    'tablet' : IDL.Null,
    'computer' : IDL.Null,
    'phone' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
  });
  const HealthMetrics = IDL.Record({
    'bmi' : IDL.Opt(IDL.Float64),
    'sleepHoursPerNight' : IDL.Opt(IDL.Float64),
    'eyeStrainSymptoms' : IDL.Opt(IDL.Bool),
    'exerciseHoursPerWeek' : IDL.Opt(IDL.Float64),
  });
  const Time = IDL.Int;
  const ScreenTimeEntry = IDL.Record({
    'minutes' : IDL.Nat,
    'device' : DeviceType,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addScreenTimeEntry' : IDL.Func([DeviceType, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHealthMetrics' : IDL.Func([], [IDL.Opt(HealthMetrics)], ['query']),
    'getRiskScore' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
    'getScreenTime' : IDL.Func([], [IDL.Vec(ScreenTimeEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitHealthMetrics' : IDL.Func([HealthMetrics], [], []),
    'updateRiskScore' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };