/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DeviceType = { 'tablet' : null } |
  { 'computer' : null } |
  { 'phone' : null };
export interface HealthMetrics {
  'bmi' : [] | [number],
  'sleepHoursPerNight' : [] | [number],
  'eyeStrainSymptoms' : [] | [boolean],
  'exerciseHoursPerWeek' : [] | [number],
}
export interface ScreenTimeEntry {
  'minutes' : bigint,
  'device' : DeviceType,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'age' : [] | [bigint],
  'name' : string,
  'notes' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addScreenTimeEntry' : ActorMethod<[DeviceType, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHealthMetrics' : ActorMethod<[], [] | [HealthMetrics]>,
  'getRiskScore' : ActorMethod<[], [] | [bigint]>,
  'getScreenTime' : ActorMethod<[], Array<ScreenTimeEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitHealthMetrics' : ActorMethod<[HealthMetrics], undefined>,
  'updateRiskScore' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];